[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

[[redirects]]
  from = "/sales-page"
  to = "/sales-page.html"
  status = 200 